mall/urls.py
from django.urls import path
from . import views

app_name = "mall"

urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("cart/", views.cart_detail, name="cart_detail"),
    path("cart/<int:product_pk>/add/", views.add_to_cart, name="add_to_cart"),
    path("orders/", views.order_list, name="order_list"),
    path("orders/new", views.order_new, name="order_new"),
    path("orders/<int:pk>/pay/", views.order_pay, name="order_pay"),
    path(
        "orders/<int:order_pk>/check/<int:payment_pk>",
        views.order_check,
        name="order_check",
    ),
    path("orders/<int:pk>/", views.order_detail, name="order_detail"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

from . import settings
from django.conf.urls.static import static
from django.shortcuts import render


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("mall_test/", include("mall_test.urls")),
    path("mall/", include("mall.urls")),
    path("", TemplateView.as_view(template_name="root.html"), name="root"),
]

if settings.DEBUG:  # 디버그 모드일 때만
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mall/models.py
import logging
from functools import cached_property
from typing import List


from django.db import models
from django.core.validators import MinValueValidator
from django.db.models import UniqueConstraint, QuerySet
from uuid import uuid4

from django.http import Http404
from django.urls import reverse
from accounts.models import User
from mysite import settings
from iamport import Iamport

# 현재 소스파일이 mall/models.py 경로의 파일이니까
# __name__은 "mall.models" 문자열을 표현합니다.
logger = logging.getLogger(__name__)


# 상품에 대한 분류를 저장할 모델
# 하나의 Category는 다수의 Product를 가지는 1:N 관계
class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = verbose_name_plural = "상품 분류"


# 한 상품에 대한 정보를 저장하는 모델
class Product(models.Model):

    class Status(models.TextChoices):
        ACTIVE = "a", "정상"
        SOLD_OUT = "s", "품절"
        OBSOLETE = "o", "단종"
        INACTIVE = "i", "비활성화"

    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, db_constraint=False
    )
    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField(blank=True)  # 빈 상태 허용
    price = models.PositiveIntegerField()  # 0 포함 0 이상
    status = models.CharField(
        choices=Status.choices, default=Status.INACTIVE, max_length=1
    )
    photo = models.ImageField(
        upload_to="mall/product/photo/%Y/%m/%d/",
    )
    # 이 두 필드는 추후에 추가했는데 필수필드 이기에 1회용 디폴트 값 지정이 필요해서
    # 1번 누르고 timezone.now 입력하였음
    created_at = models.DateTimeField(
        auto_now_add=True
    )  # 생성시간 자동으로 지금 만들어주는 필드
    updated_at = models.DateTimeField(auto_now=True)  # 수정 시간 자동으로

    def __str__(self):
        return f"<{self.pk}> {self.name}"

    class Meta:
        verbose_name = verbose_name_plural = "상품"
        # 정렬은 하나의 기준으로 이루어져야 하기 때문에 매번 view단에서 쿼리셋에 정렬 지정하기보단 모델에서 정렬
        ordering = ["-pk"]


class CartProduct(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        db_constraint=False,
        related_name="cart_product_set",  # user.cart_product_set.all() = CartProduct.objects.filter(user=user) 쿼리셋과 같다.
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        db_constraint=False,
    )
    quantity = models.PositiveIntegerField(
        default=1,
        validators=[
            MinValueValidator(1),
        ],
    )

    def __str__(self):
        return f"<{self.pk}> {self.product.name} - {self.quantity}"

    # 현재 객체의
    @property  # 메서드를 속성으로 사용할 수 있게 해주는 데코레이터
    # 이거 부를 때 cartproduct.amount 이렇게 부르면 cartproduct에는 price와 quantity가 있을때는 알아서 값이 더 해짐
    def amount(self):
        return self.product.price * self.quantity

    class Meta:
        verbose_name_plural = verbose_name = "장바구니 상품"
        constraints = [
            UniqueConstraint(
                fields=("user", "product"), name="unique_user_product"
            ),  # 여러 필드를 묶어서 unique 제약사항을 줄 수 있음
        ]


class Order(models.Model):
    class Status(models.TextChoices):
        REQUESTED = "requested", "주문요청"
        FAILED_PAYMENT = "failed_payment", "결제실패"
        PAID = "paid", "결제완료"
        PREPARED_PRODUCT = "prepared_product", "상품준비중"
        SHIPPED = "shipped", "배송중"
        DELIVERED = "delivered", "배송완료"
        CANCELED = "canceled", "주문취소"

    uid = models.UUIDField(default=uuid4, editable=False)
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        db_constraint=False,
    )
    total_amount = models.PositiveIntegerField("결제금액")
    status = models.CharField(
        "진행상태",
        max_length=20,
        choices=Status.choices,
        default=Status.REQUESTED,
        db_index=True,
    )
    product_set = models.ManyToManyField(
        Product,
        through="OrderedProduct",
        blank=False,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # 반환값의 타입은 Order입니다. 반환값 타입 지정하는 코드 부분은 Order 클래스 정의가 마무리되기 전에 수행되므로
    # 문자열 Order로 반환

    # self.product_set.all() 쿼리셋은 현 주문의 상품목록입니다.
    # 덧: self.orderedproduct_set.all()이 더 적합합니다.

    def get_absolute_url(self) -> str:
        return reverse("order_detail", args=[self.pk])

    # status 필드가 REQUESTED, FAILED_PAYMENT 일 때 에만 결제를 허용
    def can_pay(self) -> bool:
        return self.status in (self.Status.REQUESTED, self.Status.FAILED_PAYMENT)

    @property
    def name(self):
        first_product = self.product_set.first()  # 현 주문의 상품 중에 첫 번째 상품
        # 쿼리셋.first() 첫 번째 상품이 없으면
        if first_product is None:
            return "등록된 상품이 없습니다."
        size = self.product_set.all().count()  # 전체 갯수
        if size < 2:  # 1건일 때
            return first_product.name
        return f"{first_product.name} 외 {size-1} 건"

    @classmethod
    def create_from_cart(
        cls, user: User, cart_product_qs: QuerySet[CartProduct]
    ) -> "Order":  # 반환값은 Order
        cart_product_list: List[CartProduct] = list(cart_product_qs)
        # total amount의 경우에는 cart_product_qs를 다 돌아야함
        total_amount = sum(cart_product.amount for cart_product in cart_product_list)
        # cls는 order 클래스를 뜻함
        order = cls.objects.create(
            user=user, total_amount=total_amount
        )  # order 클래스 새로 생성

        ordered_product_list = []
        for cart_product in cart_product_list:  # 새로운 OrderedProduct 객체를 만들거임
            product = cart_product.product
            ordered_product = OrderedProduct(
                order=order,
                product=product,
                name=product.name,
                price=product.price,
                quantity=cart_product.quantity,
            )
            ordered_product_list.append(ordered_product)

        OrderedProduct.objects.bulk_create(ordered_product_list)

        return order

    class Meta:
        ordering = ["-pk"]


class OrderedProduct(models.Model):
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        db_constraint=False,
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        db_constraint=False,
    )
    name = models.CharField(
        "상품명", max_length=100, help_text="주문 시점의 상품명을 저장합니다."
    )
    price = models.PositiveIntegerField(
        "상품가격", help_text="주문 시점의 상품가격을 저장합니다."
    )
    quantity = models.PositiveIntegerField("수량")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


# abstract 클래스는 마이그레이션시에 테이블을 생성하지 않습니다.
# 단지 상속하기 위한 목적으로만 사용됩니다.


# 포트원 결제를 적용할 모델에서는 AbstractPortonePayment를 상속만 받으면
# 포트원 결제가 지원되도록 구현
class AbstractPortonePayment(models.Model):

    class PayMethod(models.TextChoices):
        CARD = "card", "신용카드"

    # 포트원 선택지로만 상태값 구성
    class PayStatus(models.TextChoices):
        READY = "ready", "결제 준비"
        PAID = "paid", "결제 완료"
        CANCELED = "canceled", "결제 취소"
        FAILED = "failed", "결제 실패"

    # 포트원 결제 새부 내역을 meta 필드로 저장
    # models.JSONField는 리스트, 사전 자료구조 뿐만 아니라 복잡한 형태의 JSON 데이터를 저장할 수 있습니다.
    meta = models.JSONField("포트원 결제내역", default=dict, editable=False)
    # 결제 식별자 필드
    uid = models.UUIDField("쇼핑몰 결제내역", default=uuid4, editable=False)
    # 결제명
    name = models.CharField("결제명", max_length=200)
    # 결제 금액
    desired_amount = models.PositiveIntegerField("결제 금액", editable=False)
    # 구매자 이름
    buyer_name = models.CharField("구매자 이름", max_length=100, editable=False)
    # 구매자 이메일
    buyer_email = models.EmailField("구매자 이메일", editable=False)

    # choices 인자로는 PayMethod.choices를 지정하고 default 인자로는 PayMethod.CARD를 지정합니다.
    pay_method = models.CharField(
        "결제수단", max_length=20, choices=PayMethod.choices, default=PayMethod.CARD
    )
    pay_status = models.CharField(
        "결제상태", max_length=20, choices=PayStatus.choices, default=PayStatus.READY
    )
    # 완벽한 결제성공은 status=PAID 이면서, 결제 요청금액이 실 결제 금액과 정확히 일치할 때, 결제 성공이라고
    # 판단해야만 합니다. ( 해킹의 위협 때문에 )
    is_paid_ok = models.BooleanField(
        "결제성공 여부", default=False, db_index=True, editable=False
    )

    @property
    def merchant_uid(self) -> str:
        # 이렇게 str 변환을 하면 하이픈(-)이 포함된 uuid 문자열이 됩니다.
        return str(self.uid)

    # meta 내역을 갱신하고, pay_status 필드와 is_paid_ok 필드에 반영하는 메서드 구현이 필요 update 구현

    # 그냥 property만 이용하면 호출될 때 마다 iamport 인스턴스를 계속 만드는데
    # cached_property를 이용하면 self.api 속성 두번 째 접근부터는 메서드가 호출되지 않고, 캐싱된 iamport 인스턴스를 활용합니다.
    @cached_property
    def api(self):
        return Iamport(
            imp_key=settings.PORTONE_API_KEY, imp_secret=settings.PORTONE_API_SECRET
        )

    def update(self):
        # self.api.find를 통해 결제내역 조회
        # 반환값을 결제 세부내역을 받으니, self.meta 필드에 반영합니다.
        # iamport-rest-client를 활용한 API 호출시에 2개의 예외가 발생할 수 있는데
        try:
            self.meta = self.api.find(merchant_uid=self.merchant_uid)
        except (Iamport.ResponseError, Iamport.HttpError) as e:
            # 예외가 발생하면 예외를 잡아서 에러메세지와 예외정보를 지정하고,
            # Http404 에러를 발생시키겠습니다.
            logger.error(str(e), exc_info=e)
            raise Http404("포트원에서 결제내역을 찾을 수 없습니다.")
        # self.meta에 결제 세부내역이 저장되어있다
        # 왜 저장되어있는거지?
        self.pay_status = self.meta[
            "status"
        ]  # 예외가 발생하지 않는다면 이 값을 그대로 반영

        # Iamport 인스턴스에 is_paid 메서드를 지원하고 있습니다.
        # API 호출하지 않고 결제완료 여부를 판단해줌
        self.is_paid_ok = self.api.is_paid(self.desired_amount, response=self.meta)

    class Meta:
        abstract = True


# 하나의 주문의 여러번의 결제시도가 있을 수 있다
# 하나의 결제시도를 OrderPayMent와 Order와 묶겠다
# 결제시도와 묶은것임
class OrderPayment(AbstractPortonePayment):  # 상속 받았음
    order = models.ForeignKey(Order, on_delete=models.CASCADE, db_constraint=False)

    def update(self):
        super().update()
        if self.is_paid_ok:  # 완료라면
            self.order.status = Order.Status.PAID
            self.order.save()
            # 다수의 결제시도
            self.order.orderpayment_set.exclude(pk=self.pk).delete()

mall/forms.py
from django import forms
from .models import CartProduct


class CartProductForm(forms.ModelForm):
    class Meta:
        model = CartProduct
        fields = ["quantity"]

mall/templates/mall/base.html
{% extends "base.html" %}

mall/templates/mall/cart_detail.html
{% extends "mall/base.html" %}
{% load widget_tweaks %}

{% block content %}
    <h2>장바구니</h2>

    <form action="" method="post" novalidate>
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>상품명</th>
                    <th>수량</th>
                    <th>삭제여부</th>
                </tr>
            </thead>
            <tbody>
                {% csrf_token %}
                {{ formset.management_form }}
                {% for form in formset %}
                    {% for field in form.hidden_fields %}{{ field }}{% endfor %}
                    {% with form.instance as cart_product %}
                        <tr>
                            <td>{{ cart_product.product.name }}</td>

                            <td>
                                {% render_field form.quantity class+="form-control text-end" %}
                                {{ form.quantity.errors }}
                            </td>
                            <td class="text-center">{% render_field form.DELETE class+="form-check-input" %}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
            </tbody>
        </table>
        <input type="submit" class="btn btn-primary" value="장바구니 업데이트" />
    </form>


    <div class="text-end">
        <a href="{% url 'mall:order_new' %}" class="btn btn-primary">주문하기</a>
    </div>
{% endblock %}

mall/templates/mall/order_detail.html
{% extends "mall/base.html" %}
{% load humanize %}
{% block content %}
    <h2>주문내역</h2>
    <ul>
        <li>주문번호: {{ order.uid }}</li>
        <li>{{ order.total_amount|intcomma }}원</li>
        <li>{{ order.get_status_display }}</li>
    </ul>
    <table class="table table-hover table-bordered">
        <thead>
            <tr>
                <th>주문상품명</th>
                <th>상품가격</th>
                <th>주문수량</th>
            </tr>
        </thead>
        <tbody>
            {% for ordered_product in order.orderedproduct_set.all %}
                <tr>
                    <td>{{ ordered_product.name }}</td>
                    <td class="text-end">{{ ordered_product.price|intcomma }}</td>
                    <td class="text-end">{{ ordered_product.quantity|intcomma }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

mall/templates/mall/order_pay.html
{% extends "mall/base.html" %}



{% block content %}<h2>결제</h2>{% endblock %}
{% block extra-script %}
    {{ payment_props|json_script:"payment-props" }}
    <script src="https://cdn.iamport.kr/v1/iamport.js"></script>
    <script>
        (function() {
            const IMP = window.IMP;
            const next_url = "{{ next_url }}";
            IMP.init("{{ portone_shop_id }}"); //init 호출하여 초기화

            // 결제 JS코드에서는 #payment-props를 조회하여.
            // .textContent으로 JSON 문자열을 읽어옵니다.
            const json_string = document.querySelector("#payment-props").textContent;
            // JSON 문자열을 객체로 변환하고 props로 저장합니다.
            const props = JSON.parse(json_string);

            // IMP.request_pay를 호출하여 결제 프로세스를 진행합니다.
            // 첫 번째 인자로 props를 넣어주고, 두 번째 인자로 콜백함수를 지정합니다.
            IMP.request_pay(props, function(response) {
                location.href = next_url;
            });
        })();
    </script>
{% endblock %}

mall/templates/mall/product_list.html
{% extends "mall/base.html" %}
{% load humanize %}
{% load thumbnail %}
{% load django_bootstrap5 %}
{% block content %}

    <div class="modal fade" id="alert-modal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">알림</h1>
                    <button type="button"
                            class="btn-close"
                            data-bs-dismiss="modal"
                            aria-label="Close"></button>
                </div>
                <div class="modal-body"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                    <a href="{% url 'mall:cart_detail' %}" class="btn btn-primary">장바구니 보기</a>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        {% for product in product_list %}
            <div class="col-sm-6 col-lg-4 mb-3">
                <div class="card">
                    {# djlint: off #}
                    {% thumbnail product.photo "300x300" crop="center" as thumb %}
                        <img src="{{ thumb.url }}" alt="{{ product.name }} 사진" class="card-img-top object-fit-cover"/>
                        {# 이미지와 글 사이 밑 줄 만들거임 #}
                    {% endthumbnail %}
                    {# djlint: on #}

                    <div class="card-body">
                        {{ product.category.name }}
                        <div>
                            <h5 class="text-truncate">{{ product.name }}</h5>
                        </div>
                        <div class="d-flex justify-content-between">
                            <div>{{ product.price|intcomma }}원</div>
                            <div>
                                <a href="{% url 'mall:add_to_cart' product.pk %}"
                                   class="btn btn-primary cart-button">장바구니에 담기</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="mt-3 mb-3">{% bootstrap_pagination page_obj url=request.get_full_path %}</div>
{% endblock %}

{% block extra-script %}
    {##}
    {#    <script>#}
    {#    // 생성자 인자로 css_selector를 받고#}
    {#    // 생성자 내부에서 지정 css_selector의 bootstrap.Modal 인스턴스를 생성해줍니다.#}
    {#        function AlertModal(css_selector) {#}
    {#            const modal_ele = document.querySelector(css_selector)#}
    {#            const modal = new bootstrap.Modal(css_selector);#}
    {#            // Modal을 띄우고 싶을 때. show 메소드를 통해 메세지를 지정해주면.#}
    {#            // 메서드 내에서 modal-body를 변경하고 Modal을 띄워주도록 합니다.#}
    {#            // 생각해보면 이제 modal_ele는 css_selector니까 그안에 있는 값들을 조정할 수 있는게 당연함#}
    {#            this.show = function (message) {#}
    {#                modal_ele.querySelector(".modal-body").textContent = message;#}
    {#                modal.show();#}
    {#            }#}
    {#        }#}
    {#    </script>#}

    <script>
        const alert_modal = new AlertModal("#alert-modal");
        document.querySelectorAll(".cart-button").forEach(function (button){
        button.addEventListener("click", function (e){
            e.preventDefault(); {# 기본 클릭을 막음 #}
            const url = e.target.href;
            console.log("clicked : " ,e);

            fetch(url, {
                method: "POST",
                headers:{
                    "X-CSRFToken": window.csrf_token
                }
            }).then(function (response){
                 // 200이면 정상처리이니까 response.text 그대로 반환
                 // 200이 아니면 promise의 reject 호출을 통해 reject 처리를 해서 캐치로 넘어갑니다.
                 // reject가 거부
                return response.status === 200 ? response.text() : Promise.reject(response)
            }).then(function (){
               alert_modal.show("장바구니에 담았습니다.")
            }).catch(function (){
               alert_modal.show("장바구니에 담는데 실패했습니다.")
            });

        });
    });
    </script>
{% endblock %}